# Generated by Django 5.1.7 on 2025-03-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examify_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("email", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
    ]
