# Generated by Django 5.1.7 on 2025-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examify_app", "0002_usersignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersignup",
            name="history",
            field=models.FileField(blank=True, null=True, upload_to="history/"),
        ),
    ]
